### ISSUE TITLE
Trackback errors | Sim Update 5

### ISSUE THREAD

**Issue by azgoodaz** [bestdani/msfs2blend#16]
Blender not opening up models anymore? I've been on 2.83 Stable LTS of Blender for over a year now and never had issues opening models now. But I tried to open up a few aircraft models now and I just get Trackback errors now when opening up a model.

```
Traceback (most recent call last):
  File "C:\Users\Azgoodaz\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_msfs_gltf.py", line 283, in execute
    return import_msfs_gltf(context, self.filepath, self.report)
  File "C:\Users\Azgoodaz\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_msfs_gltf.py", line 255, in import_msfs_gltf
    objects = create_objects(gltf, meshes)
  File "C:\Users\Azgoodaz\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_msfs_gltf.py", line 221, in create_objects
    obj.scale = node['scale']
KeyError: 'scale'

location: <unknown location>:-1
```

**Comment by bestdani** [comment]
Can someone with the latest MSFS update maybe veryify the issue? Would be deleting / just ignoring the missing scale node in this case just work? Unfortunately I have no MSFS subscription currently due to lack of time for this hobby and cannot investigate what has been changed in the latest update.

**Comment by azgoodaz** [comment]
> Can someone with the latest MSFS update maybe veryify the issue? Would be deleting / just ignoring the missing scale node in this case just work? Unfortunately I have no MSFS subscription currently due to lack of time for this hobby and cannot investigate what has been changed in the latest update.

A non-developer fixed the issue. Maybe you can push this update? https://forums.flightsimulator.com/t/3d-livery-painting-on-the-msfs-models/257637/128

**Comment by RoscoHead** [comment]
I can confirm the problem, and that the linked version fixes it :)

**Comment by RoscoHead** [comment]
However, I notice the UV map for the prop on the 152 is massively out of scale - might this be related?
https://www.fsdeveloper.com/forum/threads/prop-texture-in-c152.453243/

**Comment by bestdani** [comment]
Since the issue seems to be caused by some missing scale node information that had been used before and now is simply ignored when they are "missing". Maybe Microsoft / Asobo changed the file format? Unfortunately there's nothing really using the glTF standard anymore in these "glTF" files anyway.

**Comment by timothyj6767** [comment]
Cannot import aircraft traceback error ..Newest update blender and the sim..
Python: Traceback (most recent call last):
  File "C:\Users\t_han\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_msfs_gltf.py", line 327, in execute
    return import_msfs_gltf(context, self.filepath, self.report)
  File "C:\Users\t_han\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_msfs_gltf.py", line 302, in import_msfs_gltf
    objects = create_objects(gltf['nodes'], meshes)
  File "C:\Users\t_han\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_msfs_gltf.py", line 238, in create_objects
    scale = node['scale']
KeyError: 'scale'

location: <unknown location>:-1

**Comment by timothyj6767** [comment]
I get this error using the latest version of blender and the latest update ..please fix..
![import_error](https://user-images.githubusercontent.com/73369461/134819118-181c4ad0-464b-4c99-89d4-72f365a5cac7.jpg)

**Comment by TotalAviationJmyt** [comment]
Do you get this on every aircraft?

**Comment by Slowe09** [comment]
> I get this error using the latest version of blender and the latest update ..please fix.. ![import_error](https://user-images.githubusercontent.com/73369461/134819118-181c4ad0-464b-4c99-89d4-72f365a5cac7.jpg)

Hey, 
I want to do my own livery too but have the same problem. I just wanted to ask if you found the solution.
