### ISSUE TITLE
Blender use this tool calls Error

### ISSUE THREAD

**Issue by mavickmai** [bestdani/msfs2blend#25]
Python: Traceback (most recent call last):
  File "C:\Users\Mavick Mai\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_msfs_gltf.py", line 673, in execute
    import_msfs_gltf(context, ImportProperties.gltf_file, self.report,
  File "C:\Users\Mavick Mai\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_msfs_gltf.py", line 619, in import_msfs_gltf
    materials = create_materials(gltf, bl_images, report,
  File "C:\Users\Mavick Mai\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_msfs_gltf.py", line 396, in create_materials
    setup_mat_nodes(bl_mat, gltf_mat, textures, images,
  File "C:\Users\Mavick Mai\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_msfs_gltf.py", line 336, in setup_mat_nodes
    p_bsdf_node = tree.nodes['Principled BSDF']
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

**Comment by vikingshotgun** [comment]
Did you ever find a solution to this? I'm getting the same problem

**Comment by mavickmai** [comment]
use blender 2.8
