### ISSUE TITLE
Cannot load any models 

### ISSUE THREAD

**Issue by jjavierweb** [bestdani/msfs2blend#28]
While trying to load a model I keep getting this issue

Python: Traceback (most recent call last):
  File "C:\Users\javier.gutierrez\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_msfs_gltf.py", line 327, in execute
    return import_msfs_gltf(context, self.filepath, self.report)
  File "C:\Users\javier.gutierrez\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_msfs_gltf.py", line 302, in import_msfs_gltf
    objects = create_objects(gltf['nodes'], meshes)
  File "C:\Users\javier.gutierrez\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_msfs_gltf.py", line 243, in create_objects
    rot = node['rotation']
KeyError: 'rotation'

location: <unknown location>:-1

I have tried the latest blender version 3.6, and 3.0.1 as well and I have the same issue, also, I do not see the plugin preferences as per the README file on the blender ADD-ONS page

**Comment by jjavierweb** [comment]
This works on blender 3.1.2
