### ISSUE TITLE
GLTF import error

### ISSUE THREAD

**Issue by HereJy** [bestdani/msfs2blend#33]
Hello, I'm trying to import model of the pilatus pc-6 but when I try to import any gltf file of this aircraft I have this error :
```Python : Traceback (most recent call last):
  File "Path\io_msfs_gltf.py", line 754, in execute
    import_msfs_gltf(context, ImportProperties.gltf_file, self.report,
  File "Path\io_msfs_gltf.py", line 619, in import_msfs_gltf
    materials = create_materials(gltf, bl_images, report,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Path\io_msfs_gltf.py", line 396, in create_materials
    setup_mat_nodes(bl_mat, gltf_mat, textures, images,
  File "Path\io_msfs_gltf.py", line 336, in setup_mat_nodes
    p_bsdf_node = tree.nodes['Principled BSDF']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'
```
The weird thing is that it's working with some aircraft like C208 and don't with some other.

**Comment by HYLeee59** [comment]
If your blender is not in English, try to switch it to English. I have the same problem and this solved it.
